### obtener todos los provinces
GET http://localhost:3000/api/provinces


### obtener un province
GET http://localhost:3000/api/provinces/61dddc92-3b57-4296-9d4b-d8b9dd168f26

### crear un nuevo province
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
  "name": "La Pampa"
}

### modificar un province (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/provinces/61dddc92-3b57-4296-9d4b-d8b9dd168f26
Content-Type: application/json

{
  "name": "Formosa" 
}

### modificar un province (PATCH - recurso parcial)
PATCH http://localhost:3000/api/provinces/61dddc92-3b57-4296-9d4b-d8b9dd168f26
Content-Type: application/json

{
  "name": "Santa Cruz"
}

### borrar un province
DELETE http://localhost:3000/api/provinces/61dddc92-3b57-4296-9d4b-d8b9dd168f26