### GET ALL
GET http://localhost:3000/api/provinces

### POST
# @name createProvince
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
  "name": "La Pampa"
}

### ID
@id = {{createProvince.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/provinces/{{id}}


### PUT
PUT  http://localhost:3000/api/provinces/{{id}}
Content-Type: application/json

{
  "name": "Rio Negro"
}

### POST2
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
  "name": "Tucumán"
}

### POST3
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
  "name": "San Juan"
}

### POST PROVINCE TO DELETE
# @name createProvinceToDelete
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
  "name": "Misiones"
}

### DELETE
@idToDelete = {{createProvinceToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/provinces/{{idToDelete}}