### GET all characters
http://localhost:3000/api/cities


### POST a character
# @name createCity
POST http://localhost:3000/api/cities
Content-Type: application/json

{
  "name": "Rosario",
  "province":"654e27ca0880972da9a187bb",
  "postal_code":"2000"
}

### ID
@id = {{createCity.response.body.data.id}}

### GET one
http://localhost:3000/api/cities/{{id}}

### GET all by province id
http://localhost:3000/api/cities/province/654e27ca0880972da9a187bb

### PUT
PUT http://localhost:3000/api/cities/{{id}}
Content-Type: application/json

{
  "name": "Venado Tuerto",
  "province": "654e27ca0880972da9a187bb",
  "postal_code":"2000"
}

### POST
POST http://localhost:3000/api/cities
Content-Type: application/json

{
  "name": "Roldan",
  "province":"654e27ca0880972da9a187bb",
  "postal_code":"2000"
}

### POST another
# @name createCityToDelete
POST http://localhost:3000/api/cities
Content-Type: application/json

{
  "name": "Santa Fe",
  "province":"654e27ca0880972da9a187bb",
  "postal_code":"2000"
}

### POST another
# @name createCityToDelete
POST http://localhost:3000/api/cities
Content-Type: application/json

{
  "name": "Cordoba",
  "province":"654e27ca0880972da9a187cc",
  "postal_code":"2000"
}
### DELETE
@idToDelete = {{createCityToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/cities/{{idToDelete}}

### PATCH
PATCH http://localhost:3000/api/cities/{{idToDelete}}
Content-Type: application/json

{
  "name": "Villa Gobernador Galvez",
  "province":"6531d4aedc98243fffe841e5",
  "postal_code":"2000"
}