### obtener todos los cities
GET http://localhost:3000/api/cities


### obtener un city
GET http://localhost:3000/api/cities/e8d391bf-a98e-4c4e-ace4-9862ef523c30

### crear un nuevo city
POST http://localhost:3000/api/cities
Content-Type: application/json

{
  "name": "Funes",
  "id_province":1,
  "postal_code":2000,
  "id": "e8d391bf-a98e-4c4e-ace4-9862ef523c54"
}

### modificar un city (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/cities/e8d391bf-a98e-4c4e-ace4-9862ef523c30
Content-Type: application/json

{
  "name": "Venado Tuerto",
  "id_Province": 1,
  "postal_code":2000
}

### modificar un city (PATCH - recurso parcial)
//PATCH http://localhost:3000/api/cities/ffd8c011-855a-4d76-b80c-325c2eb78ea4
//Content-Type: application/json

//{
//  "name": "Santa Fe"
//}

### borrar un city
DELETE http://localhost:3000/api/cities/e8d391bf-a98e-4c4e-ace4-9862ef523c30