### GET ALL
GET http://localhost:3000/api/users

### POST
# @name createUser
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Matias",
  "lastname": "Avalos",
  "dni": "42100234",
  "phone_number": "3364456345",
  "email": "m_avalos@gmail.com",
  "role": "Cliente",
  "username": "mati77",
  "password": "apolo"
}

###ID
@id = {{createUser.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/users/{{id}}

### PUT
PUT http://localhost:3000/api/users/{{id}}
Content-Type: application/json

{
  "name": "Angel",
  "lastname": "Di Maria",
  "dni": "32001254",
  "phone_number": "3412456345",
  "email": "dimaria@gmail.com",
  "role": "Cliente",
  "username": "fideo7",
  "password": "carc"
}

### POST 2
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Marcela",
  "lastname": "Juarez",
  "dni": "25221",
  "phone_number": "5523221",
  "email": "m_juarezs@gmail.com",
  "role": "Cliente",
  "username": "marjua",
  "password": "12345"
}

### POST
# @name createUserToDelete
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Miguel",
  "lastname": "Pala",
  "dni": "221215",
  "phone_number": "62312121",
  "email": "pala@gmail.com",
  "role": "Cliente",
  "username": "mpala71",
  "password": "pal"
}

### DELETE
@idToDelete = {{createUserToDelete.response.body.data.id}}

DELETE http://localhost:3000/api/users/{{idToDelete}}