### obtener todos los users
GET http://localhost:3000/api/users


### obtener un user
GET http://localhost:3000/api/users/3a7a4c51-6f50-481e-95b1-d7fcb0931233

### crear un nuevo user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Matias",
  "lastname": "Avalos",
  "dni": "42100234",
  "phone_number": "3364456345",
  "email": "m_avalos@gmail.com",
  "role": "Cliente",
  "username": "mati77",
  "password": "apolo"
}

### modificar un user (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/users/3a7a4c51-6f50-481e-95b1-d7fcb0931233
Content-Type: application/json

{
  "name": "Angel",
  "lastname": "Di Maria",
  "dni": "32001254",
  "phone_number": "3412456345",
  "email": "dimaria@gmail.com",
  "role": "Cliente",
  "username": "fideo7",
  "password": "carc"
}

### modificar un user (PATCH - recurso parcial)
//PATCH http://localhost:3000/api/users/a02b91bc-3769-4221-beb1-d7a3aeba7dad
//Content-Type: application/json

//{
//  "name": "Santa Cruz"
//}

### borrar un user
DELETE http://localhost:3000/api/users/3a7a4c51-6f50-481e-95b1-d7fcb0931233