### obtener todos los cities
GET http://localhost:3000/api/cities


### obtener un city
GET http://localhost:3000/api/cities/526a7486-d630-4f89-a205-a9ae67594bff

### crear un nuevo city
POST http://localhost:3000/api/cities
Content-Type: application/json

{
  "name": "Funes",
  "id_Province": "e8d391bf-a98e-4c4e-ace4-9862ef523c54"
}

### modificar un city (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/cities/d7f423d0-22ad-4135-a9be-47a066fd6ed0
Content-Type: application/json

{
  "name": "Venado Tuerto",
  "id_Province": "e8d391bf-a98e-4c4e-ace4-9862ef523c54"
}

### modificar un city (PATCH - recurso parcial)
//PATCH http://localhost:3000/api/cities/ffd8c011-855a-4d76-b80c-325c2eb78ea4
//Content-Type: application/json

//{
//  "name": "Santa Fe"
//}

### borrar un city
DELETE http://localhost:3000/api/cities/ffd8c011-855a-4d76-b80c-325c2eb78ea4